config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "/", to: "home#index"

  resources :leads do
    resources :events
  end
  resources :sources
  resources :states
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :user
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /sources or /sources.json
  def index
    @sources = current_user.sources.all
  end

  # GET /sources/1 or /sources/1.json
  def show
    @source = current_user.sources.find(params[:id])
    events = current_user.events.joins(:lead).where('leads.source' => @source)
    @events_breakdown = events.joins(:state).group("states.name").count
    @events_breakdown_sum = events.count
  end

  # GET /sources/new
  def new
    @source = current_user.sources.new
  end

  # GET /sources/1/edit
  def edit
    @source = current_user.sources.find(params[:id])
  end

  # POST /sources or /sources.json
  def create
    @source = current_user.sources.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: "Source was successfully created." }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1 or /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: "Source was successfully updated." }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1 or /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: "Source was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = current_user.sources.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def source_params
      params.require(:source).permit(:name, :startable)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<%= form_with(model: source) do |form| %>
  <% if source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
        <% source.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= form.text_field :name %>
    <%= form.label :name %>
  </div>

  <div class="input-field col s12">
    <label>
      <%= form.check_box :startable %>
      <span>Startable</span>
    </label>
  </div>
  <br>
  <br>
  <div class="actions input-field col s12">
    <label><%= form.submit %></label>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing Source</h1>

<%= render 'form', source: @source %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.name %></td>
        <td><%= link_to 'Show', source %></td>
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source', new_source_path %>

app/views/sources/new.html.erb
<h1>New Source</h1>

<%= render 'form', source: @source %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @source.name %>
</p>

<p>
  <strong>Startable:</strong>
  <%= @source.startable.to_s %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>

<div class="card">
  <div class="card-image waves-effect waves-block waves-light">
    <%= pie_chart @events_breakdown %>
  </div>
  <div class="card-content">
    <span class="card-title activator grey-text text-darken-4">Event Type Breakdown<i class="material-icons right">more_vert</i></span>
  </div>
  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4">Event Type Breakdown<i class="material-icons right">close</i></span>
    <p>This chart shows how many events, by type, occurred for this source.</p>
    <table>
      <thead>
        <tr>
          <th>State</th>
          <th>%</th>
        </tr>
      </thead>
      <tbody>
        <% @events_breakdown.each do |src, value| %>
          <tr>
            <td><%= src %></td>
            <td><%= (value.to_f / @events_breakdown_sum.to_f * 100).to_s(:percentage, precision: 1) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>