config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "/", to: "home#index"

  resources :leads do
    resources :events
  end
  resources :sources
  resources :states
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :source
  belongs_to :user
  has_many :events

  def current_status
    if self.events.all.count > 0
      return self.events.order(occurred: :desc, id: :desc).first.state.name
    else
      return "-"
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /leads or /leads.json
  def index
    @leads = current_user.leads.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /leads/1 or /leads/1.json
  def show
    @lead = current_user.leads.find(params[:id])
  end

  # GET /leads/new
  def new
    @lead = current_user.leads.new
  end

  # GET /leads/1/edit
  def edit
    @lead = current_user.leads.find(params[:id])
  end

  # POST /leads or /leads.json
  def create
    @lead = current_user.leads.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: "Lead was successfully created." }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: "Lead was successfully updated." }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: "Lead was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = current_user.leads.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:company, :position, :source_id, :location, :notes)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= form.text_field :company %>
    <%= form.label :company %>
  </div>

  <div class="input-field col s12">
    <%= form.text_field :position %>
    <%= form.label :position %>
  </div>

  <div class="input-field col s12">
    <%= form.collection_select(:source_id, Source.all, :id, :name, {}, {:class => 'browser-default'}) %>
    <%= form.label :source_id %>
  </div>

  <div class="input-field col s12">
    <%= form.text_field :location %>
    <%= form.label :location %>
  </div>

  <div class="input-field col s12">
    <%= form.text_area :notes %>
    <%= form.label :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leads</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Source</th>
      <th>Location</th>
      <th>Status</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= link_to lead.position, lead %></td>
        <td><%= lead.company %></td>
        <td><%= lead.source.name %></td>
        <td><%= lead.location %></td>
        <td><%= lead.current_status %></td>
        <td><%= lead.notes %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @leads %>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @lead.company %>
</p>

<p>
  <strong>Position:</strong>
  <%= @lead.position %>
</p>

<p>
  <strong>Source:</strong>
  <%= @lead.source.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @lead.location %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @lead.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lead.current_status %>
</p>

<h3>Events</h3>
<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>State</th>
    <th>Person</th>
    <th>Notes</th>
    <th>Actions</th>
  </tr>
  <% @lead.events.each do |event| %>
    <tr>
      <td><%= event.occurred %></td>
      <td><%= event.name %></td>
      <td><%= event.state.name %></td>
      <td><%= event.person %></td>
      <td><%= event.notes %></td>
      <td><%= link_to 'Delete', [event.lead, event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= render 'events/form', event: @lead.events.new, lead: @lead %>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>